"""training/orientation_baseline.py

Baseline crack orientation classifier.

Features: bounding-box aspect ratio (width / height from the crop image) and
a simple angle proxy (whether the crop is wider than it is tall).

Classifier: logistic regression trained on the TRAIN split crops and evaluated
on the VAL split crops.

⚠ IMPORTANT: All numbers below are measured on the SYNTHETIC mini-dataset
  generated by tests/conftest.py.  Real-data performance is NOT MEASURED.
  Replace this note once a real dataset is available.

Usage
-----
    python training/orientation_baseline.py \\
        --orientation_dir data/processed/orientation \\
        --output_dir reports
"""
from __future__ import annotations

import argparse
import json
import warnings
from pathlib import Path

import numpy as np
from PIL import Image
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

LABEL_MAP = {"longitudinal": 0, "transverse": 1}
LABEL_NAMES = ["longitudinal", "transverse"]


# ── feature extraction ────────────────────────────────────────────────────────


def extract_features(img_path: Path) -> list[float] | None:
    """Return [aspect_ratio, is_wider] features for a crop image."""
    try:
        img = Image.open(img_path)
        w, h = img.size
        if h == 0:
            return None
        aspect = w / h
        is_wider = float(w > h)
        return [aspect, is_wider]
    except Exception:  # noqa: BLE001
        return None


def load_split(split_dir: Path) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Load features and labels from a split directory."""
    X, y, paths = [], [], []
    for label_name, label_id in LABEL_MAP.items():
        label_dir = split_dir / label_name
        if not label_dir.exists():
            continue
        for img_path in sorted(label_dir.iterdir()):
            if img_path.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
                continue
            feats = extract_features(img_path)
            if feats is None:
                continue
            X.append(feats)
            y.append(label_id)
            paths.append(str(img_path))
    return np.array(X, dtype=float), np.array(y, dtype=int), paths


# ── main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="Baseline orientation classifier (aspect ratio + logistic regression)")
    parser.add_argument("--orientation_dir", default="data/processed/orientation")
    parser.add_argument("--output_dir", default="reports")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    orient_root = Path(args.orientation_dir)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    train_dir = orient_root / "train"
    val_dir = orient_root / "val"

    if not train_dir.exists() or not val_dir.exists():
        print(
            "WARNING: Orientation crop directories not found.\n"
            f"  Expected: {train_dir}\n          {val_dir}\n"
            "Run make_orientation_crops.py first.\n"
            "⚠ Real-data numbers are NOT MEASURED."
        )
        return

    X_train, y_train, _ = load_split(train_dir)
    X_val, y_val, _val_paths = load_split(val_dir)

    if len(X_train) == 0:
        print("No training crops found. Ensure make_orientation_crops.py has been run.")
        return

    # Train logistic regression
    clf = LogisticRegression(random_state=args.seed, max_iter=1000)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        clf.fit(X_train, y_train)

    if len(X_val) == 0:
        print("No val crops found; skipping evaluation.")
        return

    y_pred = clf.predict(X_val)

    # Metrics
    report_str = classification_report(y_val, y_pred, target_names=LABEL_NAMES, zero_division=0)
    cm = confusion_matrix(y_val, y_pred).tolist()
    acc = float(np.mean(y_pred == y_val))

    per_class: list[dict] = []
    for i, name in enumerate(LABEL_NAMES):
        mask = y_val == i
        if mask.sum() == 0:
            per_class.append({"class": name, "support": 0, "recall": None, "precision": None})
            continue
        tp = int(((y_pred == i) & mask).sum())
        fp = int(((y_pred == i) & ~mask).sum())
        fn = int(((y_pred != i) & mask).sum())
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        per_class.append({"class": name, "support": int(mask.sum()), "recall": recall, "precision": precision})

    result = {
        "data_note": (
            "⚠ Numbers measured on SYNTHETIC mini-dataset only. "
            "Real-data performance is NOT MEASURED."
        ),
        "train_samples": len(X_train),
        "val_samples": len(X_val),
        "accuracy": acc,
        "per_class": per_class,
        "confusion_matrix": cm,
        "label_names": LABEL_NAMES,
    }

    # Write JSON report
    json_path = out_dir / "orientation_baseline.json"
    json_path.write_text(json.dumps(result, indent=2), encoding="utf-8")

    # Write markdown report
    md_lines = [
        "# Orientation Baseline Report",
        "",
        "> ⚠ **All numbers are measured on the SYNTHETIC mini-dataset.**",
        "> **Real-data performance is NOT MEASURED.**",
        "",
        f"**Train samples:** {result['train_samples']}  ",
        f"**Val samples:** {result['val_samples']}  ",
        f"**Overall accuracy:** {acc:.3f}",
        "",
        "## Per-class metrics",
        "",
        "| Class | Support | Precision | Recall |",
        "|:------|--------:|----------:|-------:|",
    ]
    for pc in per_class:
        prec = f"{pc['precision']:.3f}" if pc["precision"] is not None else "—"
        rec = f"{pc['recall']:.3f}" if pc["recall"] is not None else "—"
        md_lines.append(f"| {pc['class']} | {pc['support']} | {prec} | {rec} |")

    md_lines += [
        "",
        "## sklearn classification report",
        "```",
        report_str,
        "```",
    ]
    md_path = out_dir / "orientation_baseline.md"
    md_path.write_text("\n".join(md_lines), encoding="utf-8")

    print(report_str)
    print(f"\nReports written to {json_path} and {md_path}")


if __name__ == "__main__":
    main()
